language: node_js

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - node_js: 10
      env: TASK=lint
    - node_js: 6
      env: TASK=test
    - node_js: 8
      env: TASK=test
    - node_js: 10
      env: TASK=test
    - node_js: 10
      env: TASK=build

script:
  - yarn run $TASK
